### ISSUE TITLE
Breaks Helicopters

### ISSUE THREAD

**Issue by d3x0r** [xavier630/Ocean-Liners-Factorio#1]
https://mods.factorio.com/mods/kumpu/Helicopters

Helicopters just sit in one place and take damage instead of moving.
Think it has to do with removing /adding collision masks to all 'car' types.

Disrelated; should make 'homepage' a forum thread, and then edit mod meta data(link at the far bottom) to set the git repository.

**Comment by xavier630** [comment]
Thanks for both the report and the advice. Definitely to do with that. Had the same issue with the Aircraft mod and I have to manually add exceptions. Can't see a better way though - I need to touch their cars but not their planes and have no way to determine which is which since they are all of type car.

Great idea, I'll look into it now.

Cheers,
Xavier

**Comment by xavier630** [comment]
Uploaded a new version which has exceptions for helicopters. Let me know if there still issues :)

**Comment by d3x0r** [comment]
:) when you gonna add graphics?

**Comment by xavier630** [comment]
Great question. Probably no time soon! My hope is that a texture wizard will join the cause. I've tried my hand at a few of the models in Blender, but I wasn't too happy with what I made.
